name: annotate
channels:
  - pennmem
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ffmpeg
  - ffmpeg-python
  - filelock
  - ipykernel
  - ipython
  - jinja2
  - joblib
  - jupyter_client
  - jupyter_core
  - matplotlib
  - mkl
  - networkx
  - numpy
  - pandas
  - pillow
  - pip
  - pyqt
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - sympy
  - torchaudio
  - torchvision
  - pytorch
  - tqdm
  - wheel
  - cmlreaders
  - pip:
      - flatbuffers
      - frozenlist
      - greenlet
      - huggingface-hub
      - humanfriendly
      - hyperpyyaml
      - julius
      - lazy-loader
      - librosa
      - lightning
      - lightning-utilities
      - llvmlite
      - mako
      - markdown-it-py
      - mdurl
      - memory-profiler
      - multidict
      - nltk
      - numba
      - omegaconf
      - onnxruntime
      - optuna
      - pooch
      - primepy
      - protobuf
      - pyannote-audio>=3.0.0
      - pyannote-core
      - pyannote-database
      - pyannote-metrics
      - pyannote-pipeline
      - pytorch-lightning
      - pytorch-metric-learning
      - regex
      - rich
      - safetensors
      - semver
      - sentencepiece
      - shellingham
      - soundfile
      - soxr
      - speechbrain
      - sqlalchemy
      - tabulate
      - tensorboardx
      - tokenizers
      - torch-audiomentations
      - torch-pitch-shift
      - torchmetrics
      - transformers
      - typer
      - faster-whisper
      - "whisperx @ git+https://github.com/m-bain/whisperX.git"
      - assemblyai>=0.25.0
      - yarl
